package br.com.codiub.enderecos.entity;
// Generated 24 de mar. de 2021 10:55:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Bairros generated by hbm2java
 */
@Entity
@Table(name = "BAIRROS", schema = "DBO_CC_ENDERECOS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })	
public class Bairros implements java.io.Serializable {

	private Long id;
	private Distritos distritos;
	private String nome;
	private String nomeAbreviado;
	private String usuario;
	private Date dataAlteracao;
	
	@Id
	@GenericGenerator(
			name = "SEQ_BAIRROS", 
			strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", 
			parameters = @Parameter(name = "sequence", value = "SEQ_BAIRROS")
	)
	@GeneratedValue(generator = "SEQ_BAIRROS")
	
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRITO", nullable = false)
	public Distritos getDistritos() {
		return this.distritos;
	}

	public void setDistritos(Distritos distritos) {
		this.distritos = distritos;
	}

	@Column(name = "NOME", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "NOME_ABREVIADO", length = 100)
	public String getNomeAbreviado() {
		return this.nomeAbreviado;
	}

	public void setNomeAbreviado(String nomeAbreviado) {
		this.nomeAbreviado = nomeAbreviado;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}
	
}
