package br.com.codiub.enderecos.entity;
// Generated 2 de dez. de 2020 14:47:27 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Ceps generated by hbm2java
 */
@Entity
@Table(name = "CEPS", schema = "DBO_CC_ENDERECOS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })	
public class Ceps implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 396879977202280603L;
	private Long id;
	private Bairros bairros;
	private Logradouros logradouros;
	private String cep;
	private Long numeroIni;
	private Long numeroFim;
	private String identificacao;
	private Long codigoCorreios;
	private String usuario;
	private Date dataAlteracao;

	@Id
	@GenericGenerator(
			name = "SEQ_CEPS	", 
			strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", 
			parameters = @Parameter(name = "sequence", value = "SEQ_CEPS")
	)
	@GeneratedValue(generator = "SEQ_CEPS")

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BAIRRO")
	public Bairros getBairros() {
		return this.bairros;
	}

	public void setBairros(Bairros bairros) {
		this.bairros = bairros;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOGRADOURO", nullable = false)
	public Logradouros getLogradouros() {
		return this.logradouros;
	}

	public void setLogradouros(Logradouros logradouros) {
		this.logradouros = logradouros;
	}

	@Column(name = "CEP", length = 20)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "NUMERO_INI", precision = 10, scale = 0)
	public Long getNumeroIni() {
		return this.numeroIni;
	}

	public void setNumeroIni(Long numeroIni) {
		this.numeroIni = numeroIni;
	}

	@Column(name = "NUMERO_FIM", precision = 10, scale = 0)
	public Long getNumeroFim() {
		return this.numeroFim;
	}

	public void setNumeroFim(Long numeroFim) {
		this.numeroFim = numeroFim;
	}

	@Column(name = "IDENTIFICACAO", length = 1)
	public String getIdentificacao() {
		return this.identificacao;
	}

	public void setIdentificacao(String identificacao) {
		this.identificacao = identificacao;
	}

	@Column(name = "CODIGO_CORREIOS", precision = 10, scale = 0)
	public Long getCodigoCorreios() {
		return this.codigoCorreios;
	}

	public void setCodigoCorreios(Long codigoCorreios) {
		this.codigoCorreios = codigoCorreios;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
