package br.com.codiub.enderecos.entity;
// Generated 2 de dez. de 2020 14:47:27 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Cidades generated by hbm2java
 */
@Entity
@Table(name = "CIDADES", schema = "DBO_CC_ENDERECOS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })	
public class Cidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3165568065270547618L;
	private Long id;
	private Estados estados;
	private String nome;
	private String sigla;
	private Long codigoSicom;
	private Long codigoIbge;
	private Long codigoInep;
	private String usuario;
	private Date dataAlteracao;

	public Cidades() {
	}

	public Cidades(Long id, Estados estados, String nome) {
		this.id = id;
		this.estados = estados;
		this.nome = nome;
	}

	public Cidades(Long id, Estados estados, String nome, String sigla, Long codigoSicom, Long codigoIbge,
			Long codigoInep, String usuario, Date dataAlteracao, Set<Distritos> distritoses) {
		this.id = id;
		this.estados = estados;
		this.nome = nome;
		this.sigla = sigla;
		this.codigoSicom = codigoSicom;
		this.codigoIbge = codigoIbge;
		this.codigoInep = codigoInep;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
	}

	@Id
	@GeneratedValue(generator = "SEQ_CIDADES")
	@SequenceGenerator(name = "SEQ_CIDADES", sequenceName = "SEQ_CIDADES", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESTADO", nullable = false)
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	@Column(name = "NOME", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "SIGLA", length = 5)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "CODIGO_SICOM", precision = 10, scale = 0)
	public Long getCodigoSicom() {
		return this.codigoSicom;
	}

	public void setCodigoSicom(Long codigoSicom) {
		this.codigoSicom = codigoSicom;
	}

	@Column(name = "CODIGO_IBGE", precision = 10, scale = 0)
	public Long getCodigoIbge() {
		return this.codigoIbge;
	}

	public void setCodigoIbge(Long codigoIbge) {
		this.codigoIbge = codigoIbge;
	}

	@Column(name = "CODIGO_INEP", precision = 10, scale = 0)
	public Long getCodigoInep() {
		return this.codigoInep;
	}

	public void setCodigoInep(Long codigoInep) {
		this.codigoInep = codigoInep;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
