package br.com.codiub.enderecos.entity;
// Generated 2 de dez. de 2020 14:47:27 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Distritos generated by hbm2java
 */
@Entity
@Table(name = "DISTRITOS", schema = "DBO_CC_ENDERECOS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })	
public class Distritos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 65685635820762045L;
	private Long id;
	private Cidades cidades;
	private String nome;
	private Long codigoInep;
	private String usuario;
	private Date dataAlteracao;
	
	@Id
	@GenericGenerator(
			name = "SEQ_DISTRITOS", 
			strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", 
			parameters = @Parameter(name = "sequence", value = "SEQ_DISTRITOS")
	)
	@GeneratedValue(generator = "SEQ_DISTRITOS")

	//@SequenceGenerator(name = "SEQ_DISTRITOS", sequenceName = "SEQ_DISTRITOS", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIDADE", nullable = false)
	public Cidades getCidades() {
		return this.cidades;
	}

	public void setCidades(Cidades cidades) {
		this.cidades = cidades;
	}

	@Column(name = "NOME", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "CODIGO_INEP", precision = 10, scale = 0)
	public Long getCodigoInep() {
		return this.codigoInep;
	}

	public void setCodigoInep(Long codigoInep) {
		this.codigoInep = codigoInep;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
