package br.com.codiub.enderecos.entity;
// Generated 2 de dez. de 2020 14:47:27 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Logradouros generated by hbm2java
 */
@Entity
@Table(name = "LOGRADOUROS", schema = "DBO_CC_ENDERECOS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })	
public class Logradouros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1350169291013898546L;
	private Long id;
	private Distritos distritos;
	private TiposLogradouros tiposLogradouros;
	private String nome;
	private String preposicao;
	private String tituloPatente;
	private String nomeReduzido;
	private String nomeSimplificado;
	private String complemento;
	private String usuario;
	private Date dataAlteracao;

	
	@Id
	@GenericGenerator(
	name = "SEQ_LOGRADOUROS", 
	strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", 
	parameters = @Parameter(name = "sequence", value = "SEQ_LOGRADOUROS")
	)
	@GeneratedValue(generator = "SEQ_LOGRADOUROS")

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRITO", nullable = false)
	public Distritos getDistritos() {
		return this.distritos;
	}

	public void setDistritos(Distritos distritos) {
		this.distritos = distritos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_LOGRADOURO", nullable = false)
	public TiposLogradouros getTiposLogradouros() {
		return this.tiposLogradouros;
	}

	public void setTiposLogradouros(TiposLogradouros tiposLogradouros) {
		this.tiposLogradouros = tiposLogradouros;
	}
	
	@Column(name = "NOME", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "PREPOSICAO", length = 10)
	public String getPreposicao() {
		return this.preposicao;
	}

	public void setPreposicao(String preposicao) {
		this.preposicao = preposicao;
	}

	@Column(name = "TITULO_PATENTE", length = 50)
	public String getTituloPatente() {
		return this.tituloPatente;
	}

	public void setTituloPatente(String tituloPatente) {
		this.tituloPatente = tituloPatente;
	}

	@Column(name = "NOME_REDUZIDO", length = 100)
	public String getNomeReduzido() {
		return this.nomeReduzido;
	}

	public void setNomeReduzido(String nomeReduzido) {
		this.nomeReduzido = nomeReduzido;
	}

	@Column(name = "NOME_SIMPLIFICADO", length = 100)
	public String getNomeSimplificado() {
		return this.nomeSimplificado;
	}

	public void setNomeSimplificado(String nomeSimplificado) {
		this.nomeSimplificado = nomeSimplificado;
	}

	@Column(name = "COMPLEMENTO", length = 100)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
